language: generic

branches:
  only:
  - master

sudo: required
services: docker



script: |
  docker run \
  -e diffexe=diff \  
  -e TEXMFHOME=${TRAVIS_BUILD_DIR}/texmf \
  -v ${TRAVIS_BUILD_DIR}:/travis -w /travis \
  -it texlive/texlive sh -c \
  "tlmgr install fontspec graphics l3build latex latex-bin luaotfload luatex microtype opensans && l3build check -q -H"
