language: generic

branches:
  only:
  - master

sudo: required
services: docker

env:
  - TEXMFHOME=${TRAVIS_BUILD_DIR}/texmf

script: |
  docker run \
  -e diffexe=diff --env TEXMFHOME \
  -v ${TRAVIS_BUILD_DIR}:/travis -w /travis \
  -it texlive/texlive sh -c \
  "tlmgr install fontspec graphics l3build latex latex-bin luaotfload luatex microtype opensans && l3build check -q -H"
