language: generic

branches:
  only:
  - master

sudo: required
services: docker

script: |
  docker run \
  -e diffexe=diff \
  -v ${TRAVIS_BUILD_DIR}:/travis -w /travis \
  -it texlive/texlive sh -c \
  "tlmgr install latex latex-bin luatex l3build; l3build check -q -H"
