language: generic

branches:
  only:
  - master

sudo: required
services: docker

install:
 - source texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
 - l3build check -q -H
